# Generated by Django 3.0.5 on 2020-04-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200429_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='optional_photo1',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='optional_photo2',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='optional_photo3',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='optional_photo4',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='optional_photo5',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='optional_photo6',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
